In [1]:
import pandas as pd
import numpy as np

# Display all columns while working
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [2]:
df = pd.read_csv("../data/raw/GlobalFindexDatabase2025.csv")

C:\Users\User\AppData\Local\Temp\ipykernel_12284\3301791872.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/GlobalFindexDatabase2025.csv")

In [3]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.head()

Rows : 8577
Columns : 438

,countrynewwb,codewb,year,pop_adult,regionwb24_hi,incomegroupwb24,group,group2,account_t_d,fiaccount_t_d,mobileaccount_t_d,borrow_any_t_d,fin4_d,dig_acc,fin11_2a,fin11a,fin11b,fin11c,fin11f,fin11d,fin11e,fin14a,fin14b,fin14c,fin14d,fin13_1a,fin13_1b,fin26a,fin26b,fin27a,fin27b,fin17f,fin17a_17a1_d,fin17a,fin17b,fin17c,fin22d,fin22e,fin22a_22a1_22g_d,fin22a,fin22a_22g,fin22a_1,fin22b,fin22c,fin24sav,fin24fam,fin24work,fin24bor,fin24sell,fin24other,fin24aVD,fin24aSD,fin24aND,fin24aSD_ND,fin24aP,fin24aN,fin24sav_SD_ND,fin24fam_SD_ND,fin24work_SD_ND,fin24bor_SD_ND,fin24sell_SD_ND,fin24other_SD_ND,fin24sav_VD,fin24fam_VD,fin24work_VD,fin24bor_VD,fin24sell_VD,fin24other_VD,fh1,fin28,fh2,fin29,fin31a_31b,fin30,fin31a,fin31b,fin31d,fin32_33_34a,fin32_33_34b,fin32_33_34c,fin32_33_34d,fin32_33_acc,fin32_33,fin32_n33_34a,fin32_n33_34b,fin32_n33_34c,fin32_n33_34d,fin32_n33_acc,fin32_n33,fin32,fin32_acc,fin34a,fin34b,fin34c,fin34d,fin37_38_39a,fin37_38_39b,fin37_38_39c,fin37_38_39d,fin37_38_39_acc,fin37_38,fin37_39a,fin37_39b,fin37_39c,fin37_39d,fin37_39_acc,fin37,fin38_39a,fin38_39b,fin38_39c,fin38_39d,fin38_39_acc,fin38,fin2_t_d,fin42,fin42_acc,fin43a,fin43b,fin43c,fin43d,fin45a,fin45c,fin45d,fin45e,fin45b,fin25e2,fin9b,fin10,fin22g,fin22h,inactive_t_d,fing2p_acc,fing2p_card,fing2p_cash,fing2p_fin,fing2p_mob,fing2p,g20_made,g20_received,g20_any,merchant_pay,save_any_t_d,fin11_1,fin5w,fin5m,fin5lm,fin5n,fin6w,fin6m,fin6lm,fin6n,fin11_0,fin9a,fin17dw,fin17dm,fin17dlm,fin17e,fin7,fin3,fin19,fin20,fin21,fin24ba,fin24bb,fin24bc,fin24bd,fin24c,fin24d1,fin24d2,fin24d3,fin25e1,fin25e2b,fin25e3w,fin25e3m,fin25e3lm,fin25e4a,fin25e4b,fin25e4c,fin25e4d,fin25e4e,fh2a,fin31c,fin36a,fin36b,fin40a,fin40b,fin36Aa,fin36Ab,fin8,fin13aw,fin13am,fin13alm,fin13an,fin13bw,fin13bm,fin13blm,fin13bn,fin13cw,fin13cm,fin13clm,fin13cn,fin13e,fin13f,fin13f_1,fin15,fin16,fin22f,fin41,fin35,fin44,fh1_fh2,fin28_29,fin31d_s,fin32_n33_34c_s,fin34c_s,fin43c_s,fin32_acc_s,fin34a_s,fin32_33_acc_s,inactive_t_d_s,fing2p_fin_s,fin32_33_34a_s,fin32_n33_acc_s,fin37_39_acc_s,fin37_39c_s,fin31a_31b_s,fin31a_s,fin31b_s,fin32_n33_34a_s,fin37_39a_s,fin34d_s,fin32_33_34d_s,fin32_n33_34d_s,fing2p_card_s,fin37_39d_s,fin42_acc_s,fin32_33_34c_s,fin37_38_39c_s,fin38_39c_s,fing2p_acc_s,fing2p_cash_s,fin37_38_39a_s,fin37_38_39_acc_s,fin38_39a_s,fin38_39_acc_s,fin34b_s,fin32_n33_34b_s,fin43b_s,fin27b_s,fin27a_s,fin22h_s,fin28_29_s,fin28_s,fin29_s,fing2p_mob_s,fin37_38_39d_s,fin37_38_39b_s,fin37_39b_s,fin11_2a_s,fin11b_s,fin11f_s,fin11d_s,fin11e_s,fin9b_s,fin11_1_s,fin5m_s,fin6m_s,fin9a_s,fin5w_s,fin6w_s,fin17dm_s,fin17dlm_s,fin25e3w_s,fin25e3m_s,fin24d1_s,fin14d_s,fin24d2_s,fin11a_s,fin11c_s,fin5lm_s,fin6lm_s,fin17dw_s,fin14c_s,fin13_1a_s,fin13_1b_s,fin13am_s,fin13alm_s,fin13bm_s,fin13blm_s,fin13cm_s,fin13clm_s,fin21_s,fin14b_s,fin13cw_s,fin13f_s,fin14a_s,fin25e3lm_s,fin13aw_s,fin13bw_s,fin24d3_s,fin5n_s,fin6n_s,fin13f_1_s,fin32_33_34b_s,con1,con2a,con2b,con2c,con2d,con2e,con2f,con2g,con3a,con3b,con3c,con3d,con3e,con3f,con3g,con4,con5a,con5b,con6,con7,con8,con9a,con9b,con10,con11,con12d,con12w,con12m,con12lm,con13,con14,con15,con16,con17a,con17b,con17c,con17d,con18,con19,con20,con21,con22,con23,internet,con26d,con26w,con26m,con26lm,con27,con28d,con28w,con28m,con28lm,con28n,con29,con30a,con30b,con30c,con30d,con30e,con30f,con30g,con30h,con31a,con31b,con31c,con31d,con31e,con31f,con31g,con31h,con32a,con32b,con32c,con32d,con32e,con32f,con32g,con32h,con10_s,con11_s,con12d_s,con14_s,con16_s,con17a_s,con17b_s,con18_s,con19_s,con20_s,con21_s,con26d_s,con27_s,con28m_s,con30a_s,con30b_s,con30c_s,con30d_s,con30e_s,con30f_s,con30g_s,con30h_s,con31a_s,con31b_s,con31f_s,con2a_s,con15_s,con17d_s,con29_s,con31d_s,con31h_s,con32a_s,con3a_s,con4_s,con28d_s,con28w_s,con23_s,con31c_s,con2b_s,con2d_s,con26w_s,con2c_s,con2e_s,con2g_s,con5b_s,con12m_s,con26lm_s,con12w_s,con2f_s,con13_s,con26m_s,con28lm_s,con5a_s,con17c_s,con32h_s
0,Afghanistan,AFG,2011,14575546.0,South Asia (excluding high income),Low income,all,all,0.090050,0.090050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.028194,0.028194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.047083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,ALB,2011,2281010.0,Europe & Central Asia (excluding high income),Upper middle income,all,all,0.282681,0.282681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.085616,0.085616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.211240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.105931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,DZA,2011,26251587.0,Middle East & North Africa (excluding high inc...,Lower middle income,all,all,0.332861,0.332861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.043257,0.043257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.135368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Angola,AGO,2011,12779501.0,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.392035,0.392035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.159156,0.159156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.297585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.154860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Argentina,ARG,2011,30685516.0,Latin America & Caribbean (excluding high income),Upper middle income,all,all,0.331302,0.331302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.038007,0.038007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.298497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.219409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dim_country = (
    df[
        [
            "countrynewwb",
            "codewb",
            "regionwb24_hi",
            "incomegroupwb24"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

In [5]:
dim_country.head()

,countrynewwb,codewb,regionwb24_hi,incomegroupwb24
0,Afghanistan,AFG,South Asia (excluding high income),Low income
1,Albania,ALB,Europe & Central Asia (excluding high income),Upper middle income
2,Algeria,DZA,Middle East & North Africa (excluding high inc...,Lower middle income
3,Angola,AGO,Sub-Saharan Africa (excluding high income),Lower middle income
4,Argentina,ARG,Latin America & Caribbean (excluding high income),Upper middle income

In [6]:
print(dim_country.shape)

(174, 4)

In [7]:
dim_country.insert(
    0,
    "CountryID",
    range(1, len(dim_country) + 1)
)

In [8]:
dim_country.head()

,CountryID,countrynewwb,codewb,regionwb24_hi,incomegroupwb24
0,1,Afghanistan,AFG,South Asia (excluding high income),Low income
1,2,Albania,ALB,Europe & Central Asia (excluding high income),Upper middle income
2,3,Algeria,DZA,Middle East & North Africa (excluding high inc...,Lower middle income
3,4,Angola,AGO,Sub-Saharan Africa (excluding high income),Lower middle income
4,5,Argentina,ARG,Latin America & Caribbean (excluding high income),Upper middle income

In [9]:
print("Duplicate Country IDs :", dim_country["CountryID"].duplicated().sum())
print("Duplicate Country Codes :", dim_country["codewb"].duplicated().sum())
print("Null Values\n")
print(dim_country.isnull().sum())

Duplicate Country IDs : 0
Duplicate Country Codes : 0
Null Values

CountryID           0
countrynewwb        0
codewb              0
regionwb24_hi      12
incomegroupwb24    12
dtype: int64

In [10]:
dim_date = (
    df[["year"]]
    .drop_duplicates()
    .sort_values("year")
    .reset_index(drop=True)
)

In [11]:
dim_date.insert(
    0,
    "YearID",
    range(1, len(dim_date) + 1)
)

In [12]:
dim_date

   YearID  year
0       1  2011
1       2  2014
2       3  2017
3       4  2021
4       5  2022
5       6  2024

In [13]:
dim_demo = (
    df[
        [
            "group",
            "group2"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

In [14]:
dim_demo.insert(
    0,
    "GroupID",
    range(1, len(dim_demo) + 1)
)

In [15]:
dim_demo

    GroupID       group                 group2
0         1         all                    all
1         2      gender                    men
2         3      gender                  women
3         4      income            richest 60%
4         5      income            poorest 40%
5         6     age_cat                age 25+
6         7     age_cat             ages 15-24
7         8  urbanicity                  rural
8         9  urbanicity                  urban
9        10  laborforce      out of laborforce
10       11  laborforce          in laborforce
11       12   education  secondary edu or more
12       13   education       prim edu or less

In [16]:
fact = df.copy()

In [17]:
fact = fact.merge(
    dim_country,
    on=[
        "countrynewwb",
        "codewb",
        "regionwb24_hi",
        "incomegroupwb24"
    ],
    how="left"
)

In [18]:
fact[["countrynewwb", "CountryID"]].head()

  countrynewwb  CountryID
0  Afghanistan          1
1      Albania          2
2      Algeria          3
3       Angola          4
4    Argentina          5

In [19]:
fact = fact.merge(
    dim_date,
    on="year",
    how="left"
)

In [20]:
fact[["year", "YearID"]].head()

   year  YearID
0  2011       1
1  2011       1
2  2011       1
3  2011       1
4  2011       1

In [21]:
fact = fact.merge(
    dim_demo,
    on=[
        "group",
        "group2"
    ],
    how="left"
)

In [22]:
fact[["group", "group2", "GroupID"]].head()

  group group2  GroupID
0   all    all        1
1   all    all        1
2   all    all        1
3   all    all        1
4   all    all        1

In [23]:
print("Missing CountryID :", fact["CountryID"].isnull().sum())
print("Missing YearID    :", fact["YearID"].isnull().sum())
print("Missing GroupID   :", fact["GroupID"].isnull().sum())

Missing CountryID : 0
Missing YearID    : 0
Missing GroupID   : 0

In [24]:
fact.drop(
    columns=[
        "countrynewwb",
        "codewb",
        "regionwb24_hi",
        "incomegroupwb24",
        "year",
        "group",
        "group2"
    ],
    inplace=True
)

In [25]:
key_columns = ["CountryID", "YearID", "GroupID"]

other_columns = [col for col in fact.columns if col not in key_columns]

fact = fact[key_columns + other_columns]

In [26]:
print(fact.shape)
fact.head()

(8577, 434)

,CountryID,YearID,GroupID,pop_adult,account_t_d,fiaccount_t_d,mobileaccount_t_d,borrow_any_t_d,fin4_d,dig_acc,fin11_2a,fin11a,fin11b,fin11c,fin11f,fin11d,fin11e,fin14a,fin14b,fin14c,fin14d,fin13_1a,fin13_1b,fin26a,fin26b,fin27a,fin27b,fin17f,fin17a_17a1_d,fin17a,fin17b,fin17c,fin22d,fin22e,fin22a_22a1_22g_d,fin22a,fin22a_22g,fin22a_1,fin22b,fin22c,fin24sav,fin24fam,fin24work,fin24bor,fin24sell,fin24other,fin24aVD,fin24aSD,fin24aND,fin24aSD_ND,fin24aP,fin24aN,fin24sav_SD_ND,fin24fam_SD_ND,fin24work_SD_ND,fin24bor_SD_ND,fin24sell_SD_ND,fin24other_SD_ND,fin24sav_VD,fin24fam_VD,fin24work_VD,fin24bor_VD,fin24sell_VD,fin24other_VD,fh1,fin28,fh2,fin29,fin31a_31b,fin30,fin31a,fin31b,fin31d,fin32_33_34a,fin32_33_34b,fin32_33_34c,fin32_33_34d,fin32_33_acc,fin32_33,fin32_n33_34a,fin32_n33_34b,fin32_n33_34c,fin32_n33_34d,fin32_n33_acc,fin32_n33,fin32,fin32_acc,fin34a,fin34b,fin34c,fin34d,fin37_38_39a,fin37_38_39b,fin37_38_39c,fin37_38_39d,fin37_38_39_acc,fin37_38,fin37_39a,fin37_39b,fin37_39c,fin37_39d,fin37_39_acc,fin37,fin38_39a,fin38_39b,fin38_39c,fin38_39d,fin38_39_acc,fin38,fin2_t_d,fin42,fin42_acc,fin43a,fin43b,fin43c,fin43d,fin45a,fin45c,fin45d,fin45e,fin45b,fin25e2,fin9b,fin10,fin22g,fin22h,inactive_t_d,fing2p_acc,fing2p_card,fing2p_cash,fing2p_fin,fing2p_mob,fing2p,g20_made,g20_received,g20_any,merchant_pay,save_any_t_d,fin11_1,fin5w,fin5m,fin5lm,fin5n,fin6w,fin6m,fin6lm,fin6n,fin11_0,fin9a,fin17dw,fin17dm,fin17dlm,fin17e,fin7,fin3,fin19,fin20,fin21,fin24ba,fin24bb,fin24bc,fin24bd,fin24c,fin24d1,fin24d2,fin24d3,fin25e1,fin25e2b,fin25e3w,fin25e3m,fin25e3lm,fin25e4a,fin25e4b,fin25e4c,fin25e4d,fin25e4e,fh2a,fin31c,fin36a,fin36b,fin40a,fin40b,fin36Aa,fin36Ab,fin8,fin13aw,fin13am,fin13alm,fin13an,fin13bw,fin13bm,fin13blm,fin13bn,fin13cw,fin13cm,fin13clm,fin13cn,fin13e,fin13f,fin13f_1,fin15,fin16,fin22f,fin41,fin35,fin44,fh1_fh2,fin28_29,fin31d_s,fin32_n33_34c_s,fin34c_s,fin43c_s,fin32_acc_s,fin34a_s,fin32_33_acc_s,inactive_t_d_s,fing2p_fin_s,fin32_33_34a_s,fin32_n33_acc_s,fin37_39_acc_s,fin37_39c_s,fin31a_31b_s,fin31a_s,fin31b_s,fin32_n33_34a_s,fin37_39a_s,fin34d_s,fin32_33_34d_s,fin32_n33_34d_s,fing2p_card_s,fin37_39d_s,fin42_acc_s,fin32_33_34c_s,fin37_38_39c_s,fin38_39c_s,fing2p_acc_s,fing2p_cash_s,fin37_38_39a_s,fin37_38_39_acc_s,fin38_39a_s,fin38_39_acc_s,fin34b_s,fin32_n33_34b_s,fin43b_s,fin27b_s,fin27a_s,fin22h_s,fin28_29_s,fin28_s,fin29_s,fing2p_mob_s,fin37_38_39d_s,fin37_38_39b_s,fin37_39b_s,fin11_2a_s,fin11b_s,fin11f_s,fin11d_s,fin11e_s,fin9b_s,fin11_1_s,fin5m_s,fin6m_s,fin9a_s,fin5w_s,fin6w_s,fin17dm_s,fin17dlm_s,fin25e3w_s,fin25e3m_s,fin24d1_s,fin14d_s,fin24d2_s,fin11a_s,fin11c_s,fin5lm_s,fin6lm_s,fin17dw_s,fin14c_s,fin13_1a_s,fin13_1b_s,fin13am_s,fin13alm_s,fin13bm_s,fin13blm_s,fin13cm_s,fin13clm_s,fin21_s,fin14b_s,fin13cw_s,fin13f_s,fin14a_s,fin25e3lm_s,fin13aw_s,fin13bw_s,fin24d3_s,fin5n_s,fin6n_s,fin13f_1_s,fin32_33_34b_s,con1,con2a,con2b,con2c,con2d,con2e,con2f,con2g,con3a,con3b,con3c,con3d,con3e,con3f,con3g,con4,con5a,con5b,con6,con7,con8,con9a,con9b,con10,con11,con12d,con12w,con12m,con12lm,con13,con14,con15,con16,con17a,con17b,con17c,con17d,con18,con19,con20,con21,con22,con23,internet,con26d,con26w,con26m,con26lm,con27,con28d,con28w,con28m,con28lm,con28n,con29,con30a,con30b,con30c,con30d,con30e,con30f,con30g,con30h,con31a,con31b,con31c,con31d,con31e,con31f,con31g,con31h,con32a,con32b,con32c,con32d,con32e,con32f,con32g,con32h,con10_s,con11_s,con12d_s,con14_s,con16_s,con17a_s,con17b_s,con18_s,con19_s,con20_s,con21_s,con26d_s,con27_s,con28m_s,con30a_s,con30b_s,con30c_s,con30d_s,con30e_s,con30f_s,con30g_s,con30h_s,con31a_s,con31b_s,con31f_s,con2a_s,con15_s,con17d_s,con29_s,con31d_s,con31h_s,con32a_s,con3a_s,con4_s,con28d_s,con28w_s,con23_s,con31c_s,con2b_s,con2d_s,con26w_s,con2c_s,con2e_s,con2g_s,con5b_s,con12m_s,con26lm_s,con12w_s,con2f_s,con13_s,con26m_s,con28lm_s,con5a_s,con17c_s,con32h_s
0,1,1,1,14575546.0,0.090050,0.090050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.028194,0.028194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.047083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,1,2281010.0,0.282681,0.282681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.085616,0.085616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.211240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.105931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,1,26251587.0,0.332861,0.332861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.043257,0.043257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.135368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,1,12779501.0,0.392035,0.392035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.159156,0.159156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.297585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.154860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,1,30685516.0,0.331302,0.331302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.038007,0.038007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.298497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.219409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
import os

output_folder = "../data/processed"

os.makedirs(output_folder, exist_ok=True)

In [28]:
dim_country.to_csv(
    f"{output_folder}/DimCountry.csv",
    index=False
)

In [29]:
dim_date.to_csv(
    f"{output_folder}/DimDate.csv",
    index=False
)

In [30]:
dim_demo.to_csv(
    f"{output_folder}/DimDemographic.csv",
    index=False
)

In [31]:
fact.to_csv(
    f"{output_folder}/FactFinancialIndicators.csv",
    index=False
)

In [32]:
import os

print(os.listdir(output_folder))

['DimCountry.csv', 'DimDate.csv', 'DimDemographic.csv', 'FactFinancialIndicators.csv']